name: worflow overview

on: 
  workflow_dispatch:
  push:
     branches:
        - main
jobs:
  my_self-hosted_job:
      name: my simple job name 3
      runs-on: self-hosted
      steps: 
         - name: step in a self-hosted runner
           id: selfHosted
           shell: cmd
           run: |
              echo this is a multiline comment
              echo and this job has been executed from my sel-hosted runner
         
  A_Simple_Job:
      name: my simple job name
      runs-on: ubuntu-latest
      steps:
        - name: name of my step
          id: stepid
          run: echo "this is the first step from the first job"
        - name: python
          id: shellStep
          shell: python
          run: print("this step is using the python shell")
  A_Simple_Job2:
      name: my simple job name2
      runs-on: ubuntu-latest
      steps:
        - name: name of my step
          id: stepid
          run: echo "this is the first step from the first job"
        - name: python
          id: shellStep
          shell: python
          run: print("this step is using the python shell")

